Tensorflow Creation Opreations:
1.Constant is a immutable tensor with fixed values and datatype
2.Zeros a tensor filled with a given shape
3.Ones is a tensor that creates ones in a given shape
4.Fill is a tensor where all elements have the same specified value
5.Range is a tensor it will generate the sequential values
6.Random uniform tensor is a tensor it will create a random values from a uniform distribution
7.Random normal tensor it will create a random values from a normal distribution

In [1]:
import tensorflow as tf

# Constant tensor
a = tf.constant([1, 2, 3])
print("Constant:", a)

# Zeros tensor
z = tf.zeros((2, 3))
print("Zeros:\n", z)

# Ones tensor
o = tf.ones((2, 3))
print("Ones:\n", o)

# Fill tensor
f = tf.fill((2, 2), 5)
print("Fill:\n", f)

# Range tensor
r = tf.range(0, 6, 2)
print("Range:", r)

# Random uniform tensor
u = tf.random.uniform((2, 2))
print("Random Uniform:\n", u)

# Random normal tensor
n = tf.random.normal((2, 2))
print("Random Normal:\n", n)

Constant: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Fill:
 tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32)
Range: tf.Tensor([0 2 4], shape=(3,), dtype=int32)
Random Uniform:
 tf.Tensor(
[[0.10252309 0.4453025 ]
 [0.20840657 0.06610799]], shape=(2, 2), dtype=float32)
Random Normal:
 tf.Tensor(
[[ 0.50132376 -1.254974  ]
 [ 0.07759862  0.45979005]], shape=(2, 2), dtype=float32)


Type Casting
It converts the one type of form into another one

In [11]:
import tensorflow as tf

x = tf.constant([1, 2, 3])
print("Original dtype:", x.dtype)

y = tf.cast(x, tf.float32)
print("After casting:", y)
print("New dtype:", y.dtype)

Original dtype: <dtype: 'int32'>
After casting: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
New dtype: <dtype: 'float32'>


Indexing & Slicing

Indexing - It Accesses individual elements of a tensor using indices

Slicing - It extracts the subsets of tensor data using ranges

In [4]:
import tensorflow as tf

# 1D tensor
a = tf.constant([10, 20, 30, 40])
print("Tensor:", a)
print("Index [1]:", a[1])
print("Slice [1:3]:", a[1:3])

# 2D tensor
b = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
print("2D Tensor:\n", b)
print("Element b[1,2]:", b[1, 2])
print("Row slice:", b[0, :])

Tensor: tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)
Index [1]: tf.Tensor(20, shape=(), dtype=int32)
Slice [1:3]: tf.Tensor([20 30], shape=(2,), dtype=int32)
2D Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Element b[1,2]: tf.Tensor(6, shape=(), dtype=int32)
Row slice: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Shape Manipulation
1.reshape will changes the shape of a tensor without changing the actual data
2.expand dimensions will add the new dimensions to the particular axis
3.squeeze will remove 1 dimension from the axis

In [12]:
import tensorflow as tf

x = tf.constant([1, 2, 3, 4])

# Reshape
r = tf.reshape(x, (2, 2))
print("Reshaped:\n", r)

# Expand dimensions
e = tf.expand_dims(x, axis=0)
print("Expanded dims:\n", e)

# Squeeze
s = tf.constant([[[5]]])
sq = tf.squeeze(s)
print("Squeezed:", sq)

Reshaped:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Expanded dims:
 tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
Squeezed: tf.Tensor(5, shape=(), dtype=int32)


Mathematical Operations
1. addition of numbers
2. subtraction of numbers
3. multiplication of numbers
4. division of numbers
5. squaring of the two or more numbers
6. reduce.sum - calculating all the summed elements
7. reduce.mean - calculating the mean from the given data
8. reduce.max - finding the maximun number from the data
9. reduce.min - finding the minimun number from the data

In [7]:
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print("Add:", tf.add(a, b))
print("Subtract:", tf.subtract(b, a))
print("Multiply:", tf.multiply(a, b))
print("Divide:", tf.divide(b, a))
print("Square:", tf.square(a))

print("Reduce Sum:", tf.reduce_sum(a))
print("Reduce Mean:", tf.reduce_mean(a))
print("Reduce Max:", tf.reduce_max(a))
print("Reduce Min:", tf.reduce_min(a))

Add: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtract: tf.Tensor([3 3 3], shape=(3,), dtype=int32)
Multiply: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Divide: tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)
Square: tf.Tensor([1 4 9], shape=(3,), dtype=int32)
Reduce Sum: tf.Tensor(6, shape=(), dtype=int32)
Reduce Mean: tf.Tensor(2, shape=(), dtype=int32)
Reduce Max: tf.Tensor(3, shape=(), dtype=int32)
Reduce Min: tf.Tensor(1, shape=(), dtype=int32)


Matrix Operations
1. matmul - doing matrix multiplication
2. transpose - swaps rows and columns of a tensor

In [13]:
import tensorflow as tf

a = tf.constant([[1, 2],
                 [3, 4]])

b = tf.constant([[5, 6],
                 [7, 8]])

print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Matrix multiplication
print("MatMul:\n", tf.matmul(a, b))

# Using @ operator
print("Using @:\n", a @ b)

# Transpose
print("Transpose A:\n", tf.transpose(a))

Matrix A:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Matrix B:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
MatMul:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Using @:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Transpose A:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


Concatenation & Splitting
1. concat - 

In [9]:
import tensorflow as tf

a = tf.constant([1, 2])
b = tf.constant([3, 4])

# Concatenate
c = tf.concat([a, b], axis=0)
print("Concat:", c)

# Stack
s = tf.stack([a, b], axis=0)
print("Stack:\n", s)

# Split
x = tf.constant([10, 20, 30, 40])
splits = tf.split(x, 2)
print("Split:", splits)

Concat: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Stack:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Split: [<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 40], dtype=int32)>]
