<a href="https://colab.research.google.com/github/KeerthanaKambham/Neural_Networks/blob/main/With_and_without_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform element wise addition on two(2,3) tensors filled with random values

In [1]:
import tensorflow as tf

# Create two (2, 3) tensors with random values
A = tf.random.uniform((2, 3))
B = tf.random.uniform((2, 3))

# Element-wise addition
C = tf.add(A, B)        # or simply: C = A + B

print("Tensor A:\n", A)
print("\nTensor B:\n", B)
print("\nElement-wise Addition (A + B):\n", C)

Tensor A:
 tf.Tensor(
[[0.12759233 0.35796988 0.05448353]
 [0.88970244 0.1513741  0.7487782 ]], shape=(2, 3), dtype=float32)

Tensor B:
 tf.Tensor(
[[0.94579566 0.9519651  0.17590737]
 [0.04316032 0.05234599 0.612398  ]], shape=(2, 3), dtype=float32)

Element-wise Addition (A + B):
 tf.Tensor(
[[1.073388   1.309935   0.2303909 ]
 [0.93286276 0.2037201  1.3611763 ]], shape=(2, 3), dtype=float32)


In [2]:
import tensorflow as tf

# Step 1: Create two (2,3) tensors with random values
tensor1 = tf.random.uniform(shape=(2, 3))
tensor2 = tf.random.uniform(shape=(2, 3))

# Step 2: Perform element-wise addition
result = tensor1 + tensor2   # or tf.add(tensor1, tensor2)

# Step 3: Display the result
print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)
print("\nElement-wise Addition Result:\n", result)

Tensor 1:
 tf.Tensor(
[[0.12888944 0.44415832 0.44428205]
 [0.94529414 0.674865   0.9438628 ]], shape=(2, 3), dtype=float32)

Tensor 2:
 tf.Tensor(
[[0.5434619  0.97621024 0.7016133 ]
 [0.5838238  0.53183746 0.09930158]], shape=(2, 3), dtype=float32)

Element-wise Addition Result:
 tf.Tensor(
[[0.67235136 1.4203686  1.1458954 ]
 [1.529118   1.2067025  1.0431644 ]], shape=(2, 3), dtype=float32)


In [4]:
import numpy as np

# Create two (2,3) arrays with random values
A = np.random.rand(2, 3)
B = np.random.rand(2, 3)

# Element-wise addition
C = A + B        # or np.add(A, B)

# Display results
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nElement-wise Addition (A + B):\n", C)

Array A:
 [[0.74962547 0.53559725 0.60999426]
 [0.36997872 0.79889104 0.47598591]]

Array B:
 [[0.77933674 0.81844374 0.28127057]
 [0.59684846 0.98594543 0.94348999]]

Element-wise Addition (A + B):
 [[1.52896221 1.35404099 0.89126483]
 [0.96682718 1.78483647 1.4194759 ]]
